import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import { GIFEncoder, quantize, applyPalette } from 'gifenc';
import { AtlasResult, PhaserJsonHash, SpriteFrame } from '@/types';

/**
 * 1. Export JSON Hash (Phaser 3 / PixiJS standard)
 */
export function generatePhaserJson(
  atlasResult: AtlasResult,
  imageFilename: string = 'spritesheet.png'
): PhaserJsonHash {
  const framesRecord: PhaserJsonHash['frames'] = {};

  for (const pf of atlasResult.frames) {
    const filename = pf.name.endsWith('.png') ? pf.name : `${pf.name}.png`;
    framesRecord[filename] = {
      frame: {
        x: pf.packedX,
        y: pf.packedY,
        w: pf.packedW,
        h: pf.packedH,
      },
      rotated: pf.rotated || false,
      trimmed: pf.trimmed || false,
      spriteSourceSize: pf.spriteSourceSize,
      sourceSize: pf.sourceSize,
      pivot: pf.pivot || { x: 0.5, y: 1.0 },
    };
  }

  return {
    frames: framesRecord,
    meta: {
      app: 'Sprite-Forge',
      version: '1.0.0',
      image: imageFilename,
      format: 'RGBA8888',
      size: { w: atlasResult.width, h: atlasResult.height },
      scale: 1,
    },
  };
}

/**
 * 2. Export Godot 4 AtlasTexture .tres Resource
 */
export function generateGodotTres(
  atlasResult: AtlasResult,
  imageFilename: string = 'res://spritesheet.png'
): string {
  let content = `[gd_resource type="AtlasTexture" format=3]\n\n`;
  content += `[resource]\n`;
  content += `atlas = ExtResource("${imageFilename}")\n`;

  // Provide first frame or multi-frame dictionary
  if (atlasResult.frames.length > 0) {
    const f = atlasResult.frames[0];
    content += `region = Rect2(${f.packedX}, ${f.packedY}, ${f.packedW}, ${f.packedH})\n`;
    if (f.trimmed) {
      content += `margin = Rect2(${f.spriteSourceSize.x}, ${f.spriteSourceSize.y}, ${f.sourceSize.w - f.packedW}, ${f.sourceSize.h - f.packedH})\n`;
    }
  }

  return content;
}

/**
 * 3. Export CSS Spritesheet Styles
 */
export function generateCssSprites(
  atlasResult: AtlasResult,
  imageFilename: string = 'spritesheet.png'
): string {
  let css = `/* Generated by Sprite-Forge */\n`;
  css += `.sprite {\n  display: inline-block;\n  background-image: url('${imageFilename}');\n  background-repeat: no-repeat;\n}\n\n`;

  for (const pf of atlasResult.frames) {
    const className = pf.name.replace(/[^a-zA-Z0-9_-]/g, '-');
    css += `.${className} {\n`;
    css += `  width: ${pf.packedW}px;\n`;
    css += `  height: ${pf.packedH}px;\n`;
    css += `  background-position: -${pf.packedX}px -${pf.packedY}px;\n`;
    css += `}\n`;
  }

  return css;
}

/**
 * 4. Export All Frames as a ZIP Bundle
 */
export async function downloadFramesZip(
  frames: SpriteFrame[],
  zipFilename: string = 'sprite_frames.zip'
): Promise<void> {
  const zip = new JSZip();

  for (let i = 0; i < frames.length; i++) {
    const frame = frames[i];
    if (!frame.canvas) continue;

    const base64Data = frame.canvas.toDataURL('image/png').split(',')[1];
    const filename = `${frame.name || `frame_${String(i).padStart(3, '0')}`}.png`;
    zip.file(filename, base64Data, { base64: true });
  }

  const content = await zip.generateAsync({ type: 'blob' });
  saveAs(content, zipFilename);
}

/**
 * 5. Download Atlas Bundle (PNG + JSON + Godot tres) in a single ZIP
 */
export async function downloadAtlasZip(
  atlasResult: AtlasResult,
  baseName: string = 'spritesheet'
): Promise<void> {
  const zip = new JSZip();

  // 1. Atlas PNG
  const pngBase64 = atlasResult.canvas.toDataURL('image/png').split(',')[1];
  zip.file(`${baseName}.png`, pngBase64, { base64: true });

  // 2. Phaser/PixiJS JSON
  const jsonMetadata = generatePhaserJson(atlasResult, `${baseName}.png`);
  zip.file(`${baseName}.json`, JSON.stringify(jsonMetadata, null, 2));

  // 3. Godot 4 .tres
  const godotTres = generateGodotTres(atlasResult, `res://${baseName}.png`);
  zip.file(`${baseName}.tres`, godotTres);

  // 4. CSS Spritesheet
  const css = generateCssSprites(atlasResult, `${baseName}.png`);
  zip.file(`${baseName}.css`, css);

  const blob = await zip.generateAsync({ type: 'blob' });
  saveAs(blob, `${baseName}_atlas_bundle.zip`);
}

/**
 * 6. Export Animated GIF using gifenc
 */
export async function generateAndDownloadGif(
  frames: SpriteFrame[],
  fps: number = 12,
  gifFilename: string = 'animation.gif'
): Promise<void> {
  if (frames.length === 0) return;

  const validFrames = frames.filter((f) => !!f.canvas);
  if (validFrames.length === 0) return;

  // Find max canvas dimensions
  const maxW = Math.max(...validFrames.map((f) => f.canvas!.width));
  const maxH = Math.max(...validFrames.map((f) => f.canvas!.height));

  const gif = GIFEncoder();
  const delayMs = Math.round(1000 / fps);

  const helperCanvas = document.createElement('canvas');
  helperCanvas.width = maxW;
  helperCanvas.height = maxH;
  const helperCtx = helperCanvas.getContext('2d', { willReadFrequently: true });
  if (!helperCtx) return;

  for (const frame of validFrames) {
    helperCtx.clearRect(0, 0, maxW, maxH);
    // Draw centered or anchored
    const offsetX = Math.floor((maxW - frame.canvas!.width) / 2);
    const offsetY = Math.floor((maxH - frame.canvas!.height) / 2);
    helperCtx.drawImage(frame.canvas!, offsetX, offsetY);

    const { data } = helperCtx.getImageData(0, 0, maxW, maxH);

    // Quantize RGBA to 256 colors
    const palette = quantize(data, 256);
    const index = applyPalette(data, palette);

    gif.writeFrame(index, maxW, maxH, {
      palette,
      delay: delayMs,
      transparent: true,
      transparentIndex: 0,
    });
  }

  gif.finish();
  const buffer = gif.bytes();
  const blob = new Blob([buffer as unknown as BlobPart], { type: 'image/gif' });
  saveAs(blob, gifFilename);
}
